### ISSUE TITLE
No module named yaml

### ISSUE THREAD

**Issue by nguyenvuducthuy** [yamahigashi/SynopticGenerator#9]
i have this error when i test script [ make.py ] inside softimage
# ERROR : Traceback (most recent call last):
# File "<Script Block >", line 1, in <module>
# import synopticgenerator
# File "F:_sorry i need to hide this :)_\SynopticGenerator\synopticgenerator__init__.py", line 16, in <module>
# import yaml
# ImportError: No module named yaml
# \- [line 1]

**Comment by yamahigashi** [comment]
pip install PyYAML
